type: entities
title: Controls
show_header_toggle: false
entities:
  - type: section
  - entity: select.anenji_inverter_inverter_charging_priority
    name: Inverter Charging Priority
  - entity: select.anenji_inverter_inverter_load_priority
    name: Inverter Load Priority
  - type: section
  - entity: button.anenji_inverter_restart_inverter
    name: Restart Inverter
